# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d0a0dfe4-1bfa-4a9c-94c0-7431d0783cc1";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-d0a0dfe4-1bfa-4a9c-94c0-7431d0783cc1".device = "/dev/disk/by-uuid/d0a0dfe4-1bfa-4a9c-94c0-7431d0783cc1";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d0a0dfe4-1bfa-4a9c-94c0-7431d0783cc1";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-d0a0dfe4-1bfa-4a9c-94c0-7431d0783cc1";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E335-A6C7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a3791415-752c-4222-909e-d5e16bf8fbb7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
